# backend/graph/builder.py

"""
ReBio / Helicon — FULL Neo4j Graph Builder (OpenTargets-centric version)

Builds the Neo4j graph using CSVs generated by the pipeline.

Nodes:
  - Protein
  - Disease
  - TherapeuticProtein
  - Trial
  - Publication

Relations:
  - Protein -[:ASSOCIATED_WITH]-> Disease     
  - Protein -[:SIMILAR_TO]-> Protein         
  - TherapeuticProtein -[:TARGETS]-> Protein 
  - Trial -[:INVESTIGATES]-> Protein         
  - Trial -[:INVOLVES_TP]-> TherapeuticProtein
  - Publication -[:MENTIONS]-> Protein
"""

from pathlib import Path
import traceback

from backend.config import Config
from backend.graph.loaders import (
    get_driver,
    close_driver,
    ProteinLoader,
    DiseaseLoader,
    TherapeuticProteinLoader,
    TrialLoader,
    PublicationLoader,
)
from backend.graph.relation_loader import RelationLoader


# ---------------------------------------------------------
# Safe wrapper
# ---------------------------------------------------------
def _safe_load(label: str, func, *args, **kwargs):
    try:
        print(f"\n🚀 [{label}] 시작")
        func(*args, **kwargs)
        print(f"✅ [{label}] 완료")
    except Exception as e:
        print(f"❌ [{label}] 실패: {e}")
        traceback.print_exc()


# ---------------------------------------------------------
# Main builder
# ---------------------------------------------------------
def build_full_graph(
    node_root: Path | str | None = None,
    relations_root: Path | str | None = None,
):

    if node_root is None:
        node_root = Config.RAW_DATA_ROOT
    if relations_root is None:
        relations_root = Config.RAW_DATA_ROOT

    node_root = Path(node_root)
    relations_root = Path(relations_root)
    processed_root = Config.PROCESSED_DATA_ROOT

    print("\n===============================================")
    print("🧬 ReBio GraphDB Builder (OpenTargets Version)")
    print("===============================================")
    print(f"📁 Node CSV Root      : {node_root}")
    print(f"📁 Relation CSV Root  : {relations_root}")
    print(f"📁 Processed Data Root: {processed_root}")
    print(f"🔗 Neo4j URI          : {Config.NEO4J_URI}\n")

    # -------------------------------------------------
    # 1) LOAD NODES
    # -------------------------------------------------
    driver = get_driver()

    try:
        print("\n===============================================")
        print("📌 Loading Nodes")
        print("===============================================")

        csv_map = {
            "Proteins": ("proteins.csv", ProteinLoader),
            "Diseases": ("diseases.csv", DiseaseLoader),
            "TherapeuticProteins": ("therapeutic_proteins.csv", TherapeuticProteinLoader),
            "Trials": ("trials.csv", TrialLoader),
            "Publications": ("publications.csv", PublicationLoader),
        }

        for label, (filename, LoaderClass) in csv_map.items():
            path = node_root / filename
            if path.exists():
                _safe_load(label, LoaderClass(driver).load_from_csv, str(path))
            else:
                print(f"ℹ️ Optional missing: {path}")

    finally:
        close_driver()

    # -------------------------------------------------
    # 2) RELATIONS
    # -------------------------------------------------
    print("\n===============================================")
    print("🔗 Loading Relations (OpenTargets-centric)")
    print("===============================================")

    rel = RelationLoader()

    try:
        # ------------------------------- 
        # 2-1) Protein–Disease (OpenTargets)
        # -------------------------------
        ot_candidates = [
            processed_root / "disease_associations.csv",
            relations_root / "protein_disease_relations.csv",
        ]

        loaded = False
        for p in ot_candidates:
            if p.exists():
                _safe_load(
                    "Protein–Disease (OpenTargets)",
                    rel.load_protein_disease_from_csv,
                    str(p),
                )
                loaded = True
                break

        if not loaded:
            print(f"⚠️ No Protein–Disease associations found.")

        # ------------------------------- 
        # 2-2) Protein Similarity
        # -------------------------------
        sim_file = processed_root / "protein_similarity.csv"
        if sim_file.exists():
            _safe_load(
                "Protein Similarity (SIMILAR_TO)",
                rel.load_protein_similarity,
                str(sim_file),
            )
        else:
            print(f"ℹ️ Optional missing: {sim_file}")

        # ------------------------------- 
        # 2-3) TherapeuticProtein → Protein TARGETS
        # -------------------------------
        tp_targets = relations_root / "tp_targets.csv"
        if tp_targets.exists():
            _safe_load(
                "TherapeuticProtein TARGETS",
                rel.load_therapeutic_targets,
                str(tp_targets),
            )
        else:
            print(f"ℹ️ Optional missing: {tp_targets}")

        # ------------------------------- 
        # 2-4) Trial → Protein
        # -------------------------------
        tpr = relations_root / "trial_protein_relations.csv"
        if tpr.exists():
            _safe_load(
                "Trial → Protein",
                rel.load_trial_protein_relations,
                str(tpr),
            )
        else:
            print(f"ℹ️ Optional missing: {tpr}")

        # ------------------------------- 
        # 2-5) Trial → TherapeuticProtein  ← ★ 추가된 부분
        # -------------------------------
        ttr = relations_root / "trial_therapeutic_relations.csv"
        if ttr.exists():
            _safe_load(
                "Trial → TherapeuticProtein",
                rel.load_trial_therapeutic_relations,
                str(ttr),
            )
        else:
            print(f"ℹ️ Optional missing: {ttr}")

        # ------------------------------- 
        # 2-6) Publication → Protein
        # -------------------------------
        pm = relations_root / "publication_mentions.csv"
        if pm.exists():
            _safe_load(
                "Publication → Protein",
                rel.load_publication_protein_mentions,
                str(pm),
            )
        else:
            print(f"ℹ️ Optional missing: {pm}")

    finally:
        rel.close()

    print("\n===============================================")
    print("🎉 GRAPH DB BUILD COMPLETED (OpenTargets Version)")
    print("===============================================\n")


# ---------------------------------------------------------
# CLI
# ---------------------------------------------------------
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--node-root", type=str, default=str(Config.RAW_DATA_ROOT))
    parser.add_argument("--relations-root", type=str, default=str(Config.RAW_DATA_ROOT))
    args = parser.parse_args()

    build_full_graph(
        node_root=Path(args.node_root),
        relations_root=Path(args.relations_root),
    )
