# backend/graph/builder.py

"""
ReBio / Helicon — FULL Neo4j Graph Builder (TherapeuticProtein version)

Builds the graph using CSVs generated by the pipeline:
- Nodes:
    Protein, Disease, TherapeuticProtein, Trial, Publication
- Relations:
    ASSOCIATED_WITH
    TARGETS, BINDS_TO, MODULATES (TherapeuticProtein)
    SIMILAR_TO
    TRIAL relations
    PUBLICATION mentions
"""

from pathlib import Path
import traceback

from backend.config import Config
from backend.graph.loaders import (
    get_driver,
    close_driver,
    ProteinLoader,
    DiseaseLoader,
    TherapeuticProteinLoader,     # <-- NEW
    TrialLoader,
    PublicationLoader,
    RelationLoader,
)


def _safe_load(label: str, func, *args):
    """Wrapper to catch exceptions per stage."""
    try:
        print(f"\n🚀 [{label}] 시작")
        func(*args)
        print(f"✅ [{label}] 완료")
    except Exception as e:
        print(f"❌ [{label}] 실패: {e}")
        traceback.print_exc()


def build_full_graph(data_root: Path | str | None = None):
    """
    Build the whole Neo4j graph.
    """

    if data_root is None:
        data_root = Config.RAW_DATA_ROOT
    data_root = Path(data_root)

    print("\n===============================================")
    print("🧬 ReBio GraphDB Builder (TherapeuticProtein Version)")
    print("===============================================")
    print(f"📁 CSV Root: {data_root}")
    print(f"🔗 Neo4j URI: {Config.NEO4J_URI}\n")

    driver = get_driver()

    try:
        # =======================================================
        # NODE LOADERS
        # =======================================================
        print("\n===============================================")
        print("📌 Loading Nodes")
        print("===============================================")

        csv_map = {
            "Proteins": ("proteins.csv", ProteinLoader),
            "Diseases": ("diseases.csv", DiseaseLoader),
            "TherapeuticProteins": ("therapeutic_proteins.csv", TherapeuticProteinLoader),
            "Trials": ("trials.csv", TrialLoader),
            "Publications": ("publications.csv", PublicationLoader),
        }

        for label, (filename, LoaderClass) in csv_map.items():
            path = data_root / filename
            if path.exists():
                _safe_load(label, LoaderClass(driver).load_from_csv, str(path))
            else:
                print(f"⚠️ Missing: {path}")

        # =======================================================
        # RELATIONS
        # =======================================================
        print("\n===============================================")
        print("🔗 Loading Relations")
        print("===============================================")

        R = RelationLoader(driver)

        relation_map = {
            "Protein–Disease": ("protein_disease_relations.csv", R.load_protein_disease_from_csv),

            # TherapeuticProtein relationships
            "TP-TARGETS": ("tp_targets.csv", R.load_tp_targets_from_csv),
            "TP-BINDS": ("tp_binds.csv", R.load_tp_binds_from_csv),
            "TP-MODULATES": ("tp_modulates.csv", R.load_tp_modulates_from_csv),

            # Protein similarities (from GDS)
            "Protein Similarity": ("protein_similarity.csv", R.load_protein_similarity_from_csv),

            # Trials
            "Trial-Protein": ("trial_protein_relations.csv", R.load_trial_protein_from_csv),
            "Trial-TP": ("trial_tp_relations.csv", R.load_trial_tp_from_csv),

            # Publications
            "Publication Mentions": ("publication_mentions.csv", R.load_publication_mentions_from_csv),
        }

        for label, (filename, func) in relation_map.items():
            path = data_root / filename
            if path.exists():
                _safe_load(label, func, str(path))
            else:
                print(f"⚠️ Missing: {path}")

    finally:
        close_driver()

    print("\n===============================================")
    print("🎉 GRAPH DB BUILD COMPLETED")
    print("===============================================")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="ReBio Full Graph Loader (TherapeuticProtein)")
    parser.add_argument("--data-root", type=str, default=str(Config.RAW_DATA_ROOT))
    args = parser.parse_args()

    build_full_graph(data_root=Path(args.data_root))
